# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'Main.ui'
##
## Created by: Qt User Interface Compiler version 6.6.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QGroupBox, QLabel,
    QListView, QMainWindow, QMenu, QMenuBar,
    QPushButton, QRadioButton, QSizePolicy, QStatusBar,
    QTextEdit, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(812, 641)
        MainWindow.setMinimumSize(QSize(0, 600))
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.questionView = QListView(self.centralwidget)
        self.questionView.setObjectName(u"questionView")
        self.questionView.setGeometry(QRect(20, 40, 771, 261))
        self.chinaRadioButton = QRadioButton(self.centralwidget)
        self.chinaRadioButton.setObjectName(u"chinaRadioButton")
        self.chinaRadioButton.setGeometry(QRect(220, 470, 89, 20))
        self.kanaRadioButton = QRadioButton(self.centralwidget)
        self.kanaRadioButton.setObjectName(u"kanaRadioButton")
        self.kanaRadioButton.setGeometry(QRect(220, 510, 89, 20))
        self.japanRadioButton = QRadioButton(self.centralwidget)
        self.japanRadioButton.setObjectName(u"japanRadioButton")
        self.japanRadioButton.setGeometry(QRect(220, 550, 89, 20))
        self.bookComboBox = QComboBox(self.centralwidget)
        self.bookComboBox.addItem("")
        self.bookComboBox.addItem("")
        self.bookComboBox.addItem("")
        self.bookComboBox.addItem("")
        self.bookComboBox.setObjectName(u"bookComboBox")
        self.bookComboBox.setGeometry(QRect(90, 470, 69, 22))
        self.classComboBox = QComboBox(self.centralwidget)
        self.classComboBox.addItem("")
        self.classComboBox.addItem("")
        self.classComboBox.addItem("")
        self.classComboBox.addItem("")
        self.classComboBox.addItem("")
        self.classComboBox.addItem("")
        self.classComboBox.addItem("")
        self.classComboBox.addItem("")
        self.classComboBox.addItem("")
        self.classComboBox.addItem("")
        self.classComboBox.addItem("")
        self.classComboBox.addItem("")
        self.classComboBox.addItem("")
        self.classComboBox.addItem("")
        self.classComboBox.addItem("")
        self.classComboBox.addItem("")
        self.classComboBox.addItem("")
        self.classComboBox.addItem("")
        self.classComboBox.addItem("")
        self.classComboBox.addItem("")
        self.classComboBox.addItem("")
        self.classComboBox.addItem("")
        self.classComboBox.addItem("")
        self.classComboBox.addItem("")
        self.classComboBox.setObjectName(u"classComboBox")
        self.classComboBox.setGeometry(QRect(90, 500, 101, 22))
        self.countComboBox = QComboBox(self.centralwidget)
        self.countComboBox.addItem("")
        self.countComboBox.addItem("")
        self.countComboBox.addItem("")
        self.countComboBox.setObjectName(u"countComboBox")
        self.countComboBox.setGeometry(QRect(90, 530, 69, 22))
        self.book = QLabel(self.centralwidget)
        self.book.setObjectName(u"book")
        self.book.setGeometry(QRect(20, 470, 61, 16))
        self.class_2 = QLabel(self.centralwidget)
        self.class_2.setObjectName(u"class_2")
        self.class_2.setGeometry(QRect(20, 500, 61, 16))
        self.count = QLabel(self.centralwidget)
        self.count.setObjectName(u"count")
        self.count.setGeometry(QRect(20, 530, 61, 16))
        self.translateText = QTextEdit(self.centralwidget)
        self.translateText.setObjectName(u"translateText")
        self.translateText.setGeometry(QRect(90, 350, 171, 31))
        self.translate = QLabel(self.centralwidget)
        self.translate.setObjectName(u"translate")
        self.translate.setGeometry(QRect(20, 360, 49, 16))
        self.groupBox = QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(10, 430, 791, 161))
        self.groupBox.setStyleSheet(u"font: 700 12pt \"Yu Gothic UI\";")
        self.type = QLabel(self.groupBox)
        self.type.setObjectName(u"type")
        self.type.setGeometry(QRect(10, 130, 61, 16))
        self.type.setStyleSheet(u"font: 9pt \"Yu Gothic UI\";")
        self.typeComboBox = QComboBox(self.groupBox)
        self.typeComboBox.addItem("")
        self.typeComboBox.addItem("")
        self.typeComboBox.addItem("")
        self.typeComboBox.addItem("")
        self.typeComboBox.addItem("")
        self.typeComboBox.addItem("")
        self.typeComboBox.setObjectName(u"typeComboBox")
        self.typeComboBox.setGeometry(QRect(80, 130, 69, 22))
        self.typeComboBox.setStyleSheet(u"font: 9pt \"Yu Gothic UI\";")
        self.questionButton = QPushButton(self.groupBox)
        self.questionButton.setObjectName(u"questionButton")
        self.questionButton.setGeometry(QRect(700, 130, 75, 24))
        self.questionButton.setMinimumSize(QSize(75, 0))
        self.groupBox_2 = QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(9, 319, 791, 101))
        self.groupBox_2.setStyleSheet(u"font: 700 12pt \"Yu Gothic UI\";")
        self.label = QLabel(self.groupBox_2)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(440, 40, 231, 16))
        self.label.setStyleSheet(u"color: rgb(255, 0, 0);\n"
"font: 9pt \"Yu Gothic UI\";")
        self.translateButton = QPushButton(self.groupBox_2)
        self.translateButton.setObjectName(u"translateButton")
        self.translateButton.setGeometry(QRect(260, 30, 75, 31))
        self.translate_value = QLabel(self.groupBox_2)
        self.translate_value.setObjectName(u"translate_value")
        self.translate_value.setGeometry(QRect(80, 70, 701, 21))
        self.translate_value.setStyleSheet(u"font: 9pt \"Yu Gothic UI\";")
        self.translateAllButton = QPushButton(self.groupBox_2)
        self.translateAllButton.setObjectName(u"translateAllButton")
        self.translateAllButton.setGeometry(QRect(350, 30, 75, 31))
        self.groupBox_3 = QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(10, 10, 791, 301))
        self.groupBox_3.setStyleSheet(u"font: 700 12pt \"Yu Gothic UI\";")
        MainWindow.setCentralWidget(self.centralwidget)
        self.groupBox_3.raise_()
        self.groupBox_2.raise_()
        self.groupBox.raise_()
        self.bookComboBox.raise_()
        self.questionView.raise_()
        self.chinaRadioButton.raise_()
        self.kanaRadioButton.raise_()
        self.japanRadioButton.raise_()
        self.classComboBox.raise_()
        self.countComboBox.raise_()
        self.book.raise_()
        self.class_2.raise_()
        self.count.raise_()
        self.translateText.raise_()
        self.translate.raise_()
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 812, 22))
        self.menujp_word = QMenu(self.menubar)
        self.menujp_word.setObjectName(u"menujp_word")
        self.menuupload = QMenu(self.menubar)
        self.menuupload.setObjectName(u"menuupload")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menujp_word.menuAction())
        self.menubar.addAction(self.menuupload.menuAction())

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.chinaRadioButton.setText(QCoreApplication.translate("MainWindow", u"\u63d0\u95ee\u6c49\u8bd1", None))
        self.kanaRadioButton.setText(QCoreApplication.translate("MainWindow", u"\u63d0\u95ee\u5047\u540d", None))
        self.japanRadioButton.setText(QCoreApplication.translate("MainWindow", u"\u63d0\u95ee\u65e5\u672c\u5b57", None))
        self.bookComboBox.setItemText(0, QCoreApplication.translate("MainWindow", u"\u521d\u4e0a", None))
        self.bookComboBox.setItemText(1, QCoreApplication.translate("MainWindow", u"\u521d\u4e0b", None))
        self.bookComboBox.setItemText(2, QCoreApplication.translate("MainWindow", u"\u4e2d\u4e0a", None))
        self.bookComboBox.setItemText(3, QCoreApplication.translate("MainWindow", u"\u4e2d\u4e0b", None))

#if QT_CONFIG(tooltip)
        self.bookComboBox.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><br/></p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.classComboBox.setItemText(0, QCoreApplication.translate("MainWindow", u"\u7b2c\u4e00\u8bfe", None))
        self.classComboBox.setItemText(1, QCoreApplication.translate("MainWindow", u"\u7b2c\u4e8c\u8bfe", None))
        self.classComboBox.setItemText(2, QCoreApplication.translate("MainWindow", u"\u7b2c\u4e09\u8bfe", None))
        self.classComboBox.setItemText(3, QCoreApplication.translate("MainWindow", u"\u7b2c\u56db\u8bfe", None))
        self.classComboBox.setItemText(4, QCoreApplication.translate("MainWindow", u"\u7b2c\u4e94\u8bfe", None))
        self.classComboBox.setItemText(5, QCoreApplication.translate("MainWindow", u"\u7b2c\u516d\u8bfe", None))
        self.classComboBox.setItemText(6, QCoreApplication.translate("MainWindow", u"\u7b2c\u4e03\u8bfe", None))
        self.classComboBox.setItemText(7, QCoreApplication.translate("MainWindow", u"\u7b2c\u516b\u8bfe", None))
        self.classComboBox.setItemText(8, QCoreApplication.translate("MainWindow", u"\u7b2c\u4e5d\u8bfe", None))
        self.classComboBox.setItemText(9, QCoreApplication.translate("MainWindow", u"\u7b2c\u5341\u8bfe", None))
        self.classComboBox.setItemText(10, QCoreApplication.translate("MainWindow", u"\u7b2c\u5341\u4e00\u8bfe", None))
        self.classComboBox.setItemText(11, QCoreApplication.translate("MainWindow", u"\u7b2c\u5341\u4e8c\u8bfe", None))
        self.classComboBox.setItemText(12, QCoreApplication.translate("MainWindow", u"\u7b2c\u5341\u4e09\u8bfe", None))
        self.classComboBox.setItemText(13, QCoreApplication.translate("MainWindow", u"\u7b2c\u5341\u56db\u8bfe", None))
        self.classComboBox.setItemText(14, QCoreApplication.translate("MainWindow", u"\u7b2c\u5341\u4e94\u8bfe", None))
        self.classComboBox.setItemText(15, QCoreApplication.translate("MainWindow", u"\u7b2c\u5341\u516d\u8bfe", None))
        self.classComboBox.setItemText(16, QCoreApplication.translate("MainWindow", u"\u7b2c\u5341\u4e03\u8bfe", None))
        self.classComboBox.setItemText(17, QCoreApplication.translate("MainWindow", u"\u7b2c\u5341\u516b\u8bfe", None))
        self.classComboBox.setItemText(18, QCoreApplication.translate("MainWindow", u"\u7b2c\u5341\u4e5d\u8bfe", None))
        self.classComboBox.setItemText(19, QCoreApplication.translate("MainWindow", u"\u7b2c\u4e8c\u5341\u8bfe", None))
        self.classComboBox.setItemText(20, QCoreApplication.translate("MainWindow", u"\u7b2c\u4e8c\u5341\u4e00\u8bfe", None))
        self.classComboBox.setItemText(21, QCoreApplication.translate("MainWindow", u"\u7b2c\u4e8c\u5341\u4e8c\u8bfe", None))
        self.classComboBox.setItemText(22, QCoreApplication.translate("MainWindow", u"\u7b2c\u4e8c\u5341\u4e09\u8bfe", None))
        self.classComboBox.setItemText(23, QCoreApplication.translate("MainWindow", u"\u7b2c\u4e8c\u5341\u56db\u8bfe", None))

        self.countComboBox.setItemText(0, QCoreApplication.translate("MainWindow", u"10", None))
        self.countComboBox.setItemText(1, QCoreApplication.translate("MainWindow", u"15", None))
        self.countComboBox.setItemText(2, QCoreApplication.translate("MainWindow", u"20", None))

        self.book.setText(QCoreApplication.translate("MainWindow", u"\u4e66\u518c\uff1a", None))
        self.class_2.setText(QCoreApplication.translate("MainWindow", u"\u8bfe\uff1a", None))
        self.count.setText(QCoreApplication.translate("MainWindow", u"\u542c\u5199\u4e2a\u6570\uff1a", None))
        self.translate.setText(QCoreApplication.translate("MainWindow", u"\u7ffb\u8bd1\uff1a", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"\u529f\u80fd\u9009\u62e9\u533a", None))
        self.type.setText(QCoreApplication.translate("MainWindow", u"\u542c\u5199\u7c7b\u578b\uff1a", None))
        self.typeComboBox.setItemText(0, QCoreApplication.translate("MainWindow", u"ALL", None))
        self.typeComboBox.setItemText(1, QCoreApplication.translate("MainWindow", u"\u540d\u8bcd", None))
        self.typeComboBox.setItemText(2, QCoreApplication.translate("MainWindow", u"\u52a8\u8bcd", None))
        self.typeComboBox.setItemText(3, QCoreApplication.translate("MainWindow", u"\u5f62\u5bb9\u8bcd", None))
        self.typeComboBox.setItemText(4, QCoreApplication.translate("MainWindow", u"\u526f\u8bcd", None))
        self.typeComboBox.setItemText(5, QCoreApplication.translate("MainWindow", u"\u77ed\u8bed", None))

#if QT_CONFIG(whatsthis)
        self.questionButton.setWhatsThis(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><br/></p></body></html>", None))
#endif // QT_CONFIG(whatsthis)
        self.questionButton.setText(QCoreApplication.translate("MainWindow", u"\u63d0\u95ee", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("MainWindow", u"\u7ffb\u8bd1\u533a", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"\u203b\u53ea\u80fd\u7ffb\u8bd1\u63d0\u95ee\u533a\u5185\u90e8\u7684\u5355\u8bcd", None))
        self.translateButton.setText(QCoreApplication.translate("MainWindow", u"\u7ffb\u8bd1", None))
        self.translate_value.setText("")
        self.translateAllButton.setText(QCoreApplication.translate("MainWindow", u"\u5168\u90e8\u7ffb\u8bd1", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("MainWindow", u"\u63d0\u95ee\u533a", None))
        self.menujp_word.setTitle(QCoreApplication.translate("MainWindow", u"\u63d0\u95ee", None))
        self.menuupload.setTitle(QCoreApplication.translate("MainWindow", u"\u4e0a\u4f20", None))
    # retranslateUi

